######################################################################
# Automatically generated by qmake (1.02a) Wed Feb 5 13:25:20 2003
######################################################################

TEMPLATE = app

# Input
HEADERS += aa_xpm.h \
           aa_xpm_old.h \
           application.h \
           arrow.h \
           arrows.h \
           atom.h \
           bond.h \
           bondedit.h \
           boshcp.h \
           bracket.h \
           brackets.h \
           CDXConstants.h \
           cdxml_reader.h \
           chemdata.h \
           clipboard.h \
           cml.h \
           crings_dialog.h \
           curvearrow.h \
           defs.h \
           dpoint.h \
           drawable.h \
           fixeddialog.h \
           graphdata.h \
           graphdialog.h \
           graphwidget.h \
           helpwindow.h \
           http.h \
           ioiface.h \
           lines.h \
           moldata.h \
           molecule.h \
           molecule_sssr.h \
           molinfodialog.h \
           myfiledialog.h \
           na_xpm.h \
           namer.h \
           netaccess.h \
           netchoosedialog.h \
           netdialog.h \
           ngw.h \
           pagesetupdialog.h \
           paintable.h \
           peak.h \
           peptidebuilder.h \
           prefs.h \
           previewwidget.h \
           render2d.h \
           ring.h \
           ring_xpm.h \
           ringdialog.h \
           rings.h \
           sdg.h \
           setofrings.h \
           smilesdialog.h \
           sorf.h \
           sugar_xpm.h \
           symbol.h \
           symbol_xpm.h \
           text.h \
           tool_13c_nmr.h \
           tool_1h_nmr.h \
           tool_ir.h \
           tooldialog.h \
           xdc_event.h \
           xdc_toolbutton.h \
           xml_cml.h \
           xml_reader.h
SOURCES += application.cpp \
           application_ob.cpp \
           application_ring.cpp \
           arrow.cpp \
           bond.cpp \
           bondedit.cpp \
           bracket.cpp \
           cdx2cdxml.cpp \
           cdxml_reader.cpp \
           chemdata.cpp \
           chemdata_cdx.cpp \
           chemdata_cdxml.cpp \
           chemdata_cml.cpp \
           chemdata_edit.cpp \
           chemdata_event.cpp \
           chemdata_mdl.cpp \
           chemdata_rw.cpp \
           chemdata_rxn.cpp \
           chemdata_tools.cpp \
           chemdata_xdc.cpp \
           chemdata_xml.cpp \
           crings_dialog.cpp \
           curvearrow.cpp \
           drawable.cpp \
           fixeddialog.cpp \
           graphdialog.cpp \
           graphwidget.cpp \
           helpwindow.cpp \
           ioiface.cpp \
           main.cpp \
           molecule.cpp \
           molecule_1h_nmr.cpp \
           molecule_obmol.cpp \
           molecule_smiles.cpp \
           molecule_tools.cpp \
           molinfodialog.cpp \
           myfiledialog.cpp \
           namer.cpp \
           netaccess.cpp \
           netchoosedialog.cpp \
           netdialog.cpp \
           ngw.cpp \
           pagesetupdialog.cpp \
           peptidebuilder.cpp \
           previewwidget.cpp \
           render2d.cpp \
           render2d_draw.cpp \
           render2d_event.cpp \
           render2d_print.cpp \
           render2d_select.cpp \
           render2d_text.cpp \
           ringdialog.cpp \
           sdg.cpp \
           smilesdialog.cpp \
           symbol.cpp \
           text.cpp \
           tool_13c_nmr.cpp \
           tool_1h_nmr.cpp \
           tool_ir.cpp \
           tooldialog.cpp \
           xdc_toolbutton.cpp \
           xml_cml.cpp \
           xml_reader.cpp
TRANSLATIONS = xdrawchem_en.ts xdrawchem_fr.ts xdrawchem_de.ts \
	xdrawchem_pl.ts xdrawchem_nl.ts xdrawchem_it.ts xdrawchem_es.ts \
	xdrawchem_pt.ts xdrawchem_pt_BR.ts xdrawchem_da.ts xdrawchem_jp.ts
TARGET = xdrawchem
CONFIG += qt warn_on debug
ringfile.path = /usr/local/lib/xdrawchem
ringfile.files = ring/*
INSTALLS += ringfile
DEFINES += UNIX RINGHOME=\"/usr/local/lib/xdrawchem\" XDC_SERVER=\"herger.ibb.gatech.edu\"
